### ISSUE TITLE
Correct undefined footnote in Questionnaire Survey Standard

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#11]
Last line under "desirable"

**Comment by Taher-Ghaleb** [comment]
Is this issue still not fixed, @drpaulralph?

**Comment by arhamarshad1** [comment]
No, so I figured out the problem in the undefined part. So if you open Optimization Studies for example, some attributes have two footnotes in them which cause a problem for the createToolTip() function and it just reads it as "undefined". @Taher-Ghaleb

**Comment by Taher-Ghaleb** [comment]
OK, I see it now. I will fix it.

**Comment by arhamarshad1** [comment]
@Taher-Ghaleb I updated the code on the server, the Optimization Study footnotes are still undefined, is it the same on your localhost?

**Comment by Taher-Ghaleb** [comment]
They work fine on my side.

**Comment by Taher-Ghaleb** [comment]
@arhamarshad1 On the server, I still see the old code for creating tooltips. It's not updated.

**Comment by arhamarshad1** [comment]
@Taher-Ghaleb I see, it works now. Thanks!
